api:
  insecure: true
  dashboard: true
  debug: false

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

log:
  format: json
  level: DEBUG

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    watch: true
    exposedbydefault: false
    network: proxy
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true
